# Generated by Django 4.1.7 on 2023-03-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="food_ids",),
        migrations.RemoveField(model_name="order", name="id",),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.CharField(max_length=100)),
                ("delivery_state", models.CharField(max_length=10)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="takeaway.food"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="takeaway.order"
                    ),
                ),
            ],
        ),
    ]
