# Generated by Django 4.1.7 on 2023-03-16 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0002_remove_order_food_ids_remove_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 16, 20, 30, 50, 533437)
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 16, 20, 30, 50, 533437)
            ),
        ),
    ]
