# Generated by Django 4.1.7 on 2023-03-16 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0003_order_date_orderdetail_count_orderdetail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 16, 21, 49, 21, 782587)
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 16, 21, 49, 21, 782587)
            ),
        ),
    ]
