# Generated by Django 4.1.7 on 2023-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0003_remove_userprofile_website_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="discounted_price",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
