# Generated by Django 4.1.7 on 2023-03-16 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0005_alter_order_date_alter_orderdetail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 16, 22, 2, 31, 840165, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 16, 22, 2, 31, 841164, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
