# Generated by Django 4.1.7 on 2023-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0005_alter_food_discounted_price_alter_food_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="discounted_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="food", name="price", field=models.IntegerField(default=0),
        ),
    ]
