# Generated by Django 4.1.7 on 2023-03-17 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0007_checkout_alter_order_date_alter_orderdetail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 46, 44, 565018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 46, 44, 565018, tzinfo=datetime.timezone.utc)),
        ),
    ]
