# Generated by Django 4.1.7 on 2023-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0007_food_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="discounted_price",
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name="food", name="price", field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name="food", name="rating", field=models.FloatField(max_length=3),
        ),
    ]
