# Generated by Django 4.1.7 on 2023-03-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0008_alter_food_discounted_price_alter_food_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet", name="cash", field=models.FloatField(default=0),
        ),
    ]
