# Generated by Django 4.1.7 on 2023-03-17 14:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0008_remove_checkout_created_at_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 47, 41, 89660, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 47, 41, 90669, tzinfo=datetime.timezone.utc)),
        ),
    ]
