# Generated by Django 4.1.7 on 2023-03-17 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0009_checkout_created_at_alter_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 15, 10, 7, 394001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 15, 10, 7, 395002, tzinfo=datetime.timezone.utc)),
        ),
    ]
