# Generated by Django 4.1.7 on 2023-03-19 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "takeaway",
            "0010_rename_zip_code_checkout_zipcode_alter_checkout_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="order",
            name="zipcode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 18, 29, 22, 659101, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 18, 29, 22, 658104, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 18, 29, 22, 659101, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
