# Generated by Django 4.1.7 on 2023-03-19 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0011_order_address_order_city_order_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 20, 16, 38, 396717, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 20, 16, 38, 396717, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 20, 16, 38, 396717, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
