# Generated by Django 4.1.7 on 2023-03-21 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0012_alter_comment_date_alter_order_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="checkout", name="address",),
        migrations.RemoveField(model_name="order", name="address",),
        migrations.RemoveField(model_name="order", name="city",),
        migrations.RemoveField(model_name="order", name="email",),
        migrations.RemoveField(model_name="order", name="first_name",),
        migrations.RemoveField(model_name="order", name="last_name",),
        migrations.RemoveField(model_name="order", name="phone",),
        migrations.RemoveField(model_name="order", name="zipcode",),
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 21, 20, 25, 40, 415724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 21, 20, 25, 40, 415724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 21, 20, 25, 40, 415724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
