# Generated by Django 4.1.7 on 2023-03-21 21:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0013_remove_checkout_address_remove_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdetail",
            name="total_discount",
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name="cartdetail",
            name="total_price",
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 21, 21, 18, 25, 72776, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
