# Generated by Django 4.1.7 on 2023-03-22 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeaway", "0015_delete_checkout_order_city_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 22, 18, 58, 42, 769232, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
